config/routes.rb
Rails.application.routes.draw do
  resources :categories, :soups
  get '/categories/:id' => 'category#show', as: 'show_category'
  get '/soups/:id' => 'soup#show'

  root to: 'categories#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :soups
end

app/models/soup.rb
class Soup < ActiveRecord::Base
  belongs_to :categor

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/soups_controller.rb
class SoupsController < ApplicationController
  def show
    @soup = Soup.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/soups_helper.rb
module SoupsHelper
end

app/views/categories/index.html.erb
<h1>Soup Categories</h1>
<ul>
  <% @categories.each do |category| %>
    <li><%= link_to category.name, category %>(<%= category.soups.count%>)</li>
  <% end %>
</ul>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<ul>
  <% @category.soups.each do |soup| %>
  <li><%=link_to soup.name, soup%></li>
  <% end %>
</ul>
<p><%= link_to "Back to Category", categories_path %><p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SoupToBits</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/soups/show.html.erb
<h1><%= @soup.name %>
<p><%= link_to "Back to categories", categories_path %></p>